general {
    lock_cmd = pidof hyprlock || hyprlock                                     # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                  # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.disp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

# listener {
#     timeout = 590                                     # 9 minutes 50 seconds.
#     on-timeout = brightnessctl -sdq amdgpu_bl1 set 10 # set monitor backlight to minimum, avoid 0 on OLED monitor.
#     on-resume = brightnessctl -rdq amdgpu_bl1         # monitor backlight restore.
# }

# listener { 
#   timeout = 597                                                 # 9 minutes 57 seconds
#     on-timeout = brightnessctl -sdq tpacpi:kbd_backlight set 0  # turn off keyboard backlight.
#     on-resume = brightnessctl -rdq tpacpi:kbd_backlight         # turn on keyboard backlight.
# }

listener {
    timeout =  599                      # 9 minutes 59 seconds
    on-timeout = loginctl lock-session  # lock screen when timeout has passed
}

listener {
    timeout = 600                                                                         # 10 minutes
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                   # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 900                   # 15 minutes
    on-timeout = systemctl suspend  # suspend pc
}
