$font = JetBrainsMono Nerd Font Propo
$weight = weight="500"
$style = style="italic"

general {
  hide_cursor = false
  ignore_empty_input = true
  imediate_render = true
  fail_timeout = 1000
}

auth {
  pam:enabled = true
  pam:enabled = hyprlock
}

animations {
  enabled = false
}

background {
  monitor =
  path = ~/.config/wallpapers/linus.jpg
  blur_passes = 3
}

# TIME
label {
  monitor =
  text = $TIME12
  color = rgba(255, 255, 255, 1)
  font_size = 110
  font_family = $font
  position = 0, 225
  halign = center
  valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:60000] date +"%A, %B %d"
  color = rgba(255, 255, 255, 1)
  font_size = 40
  font_family = $font
  position = 0, 115
  halign = center
  valign = center
}

# Password
input-field {
  monitor =
  size = 678, 115
  outline_thickness = 2
  dots_size = .3
  dots_spacing = .25
  outer_color = rgba(250, 250, 250, 0)
  inner_color = rgba(250, 250, 250, 0.35)
  font_color = rgba(15, 15, 15, 0.90)
  font_family = $font
  fade_on_empty = false
  placeholder_text = <span $style $weight> Password and Auth-key</span>
  check_text = <span $weight foreground="##0f0f0f"> Touch Auth-Key</span>
  check_color = rgba(240, 206, 109, 0)
  fail_text = <span $weight foreground="##0f0f0f">Authentication Failed</span>
  fail_color = rgba(246, 100, 112, 0)
  position = 0%, 0%
  halign = center
  valign = center
}

# Power off
label {
  monitor =
  text = <span>  </span>
  color = rgba(255, 255, 255, 1)
  font_size = 65
  onclick = shutdown now
  position = -295, -130
  halign = center
  valign = center
}

label {
  monitor =
  text = <span>Shutdown</span>
  color = rgba(255, 255, 255, 1)
  font_size = 20
  onclick = shutdown now
  position = -278, -193
  halign = center
  valign = center
}

# Reboot
label {
  monitor =
  text = <span>  </span>
  color = rgba(255, 255, 255, 1)
  font_size = 72
  onclick = reboot now
  position = 0, -131
  halign = center
  valign = center
}

label {
  monitor =
  text = <span>Reboot</span>
  color = rgba(255, 255, 255, 1)
  font_size = 20
  onclick = shutdown now
  position = 10, -193
  halign = center
  valign = center
}

# Suspend
label {
  monitor =
  text = <span> 󰤄 </span>
  color = rgba(255, 255, 255, 1)
  font_size = 77
  onclick = systemctl suspend
  position = 286, -131
  halign = center
  valign = center
}

label {
  monitor =
  text = <span>Suspend</span>
  color = rgba(255, 255, 255, 1)
  font_size = 20
  onclick = shutdown now
  position = 289, -193
  halign = center
  valign = center
}
