#-----------------------------------------------------------------------------
# STATUS BAR
#-----------------------------------------------------------------------------

# Tokyo Night (Storm) Colorscheme
BG="#1f2335"
FG="#c0caf5"
FG_GUTTER="#3b4261"
BLACK="#414868"
GRAY="#565f89"
BLUE="#7aa2f7"
CYAN="#7dcfff"
GREEN="#9ece6a"
TEAL="#1abc9c"
YELLOW="#e0af68"
MAGENTA="#bb9af7"
PURPLE="#9d7cd8"
RED="#f7768e"
ORANGE="#ff9e64"

# Nerdfont characters
TMUX="#(printf '\uebc8')"

# General
set -g status-position top
set -g status-style bg=${BG},fg=${FG}

# Right
set -g status-right-length 100
set -g status-right "#[fg=${GRAY},bg=default]| #[fg=${GREEN},bold]#h "

# Left
set -g status-left-length 100
set -g status-left "#[fg=${GREEN},bold] ${TMUX} #S #[fg=${GRAY},nobold]| "

# Window
set -g status-justify "left"
setw -g window-status-separator " "
set -g window-status-current-format "#[fg=${BLUE},bold]#[bg=${BG}]#[underscore]#I:#W"
set -g window-status-format "#[fg=${GRAY},bg=${BG}]#I:#W"

# Message
set -g message-style "fg=${RED},bg=${FG_GUTTER},align=centre"
set -g message-command-style "fg=${RED},bg=${FG_GUTTER},align=centre"

#Pane
set -g pane-border-style "fg=${FG_GUTTER}"
set -g pane-active-border-style "fg=${BLUE}"

# Modes
set -g mode-style "fg=${BLUE},bg=${FG_GUTTER}"

#------------------------------------------------------------------------------
# CONFIG
#-----------------------------------------------------------------------------

# Bind Ctrl-a as prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# General Settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -g status-interval 5
set -g display-time 1500
set -g history-limit 100000

# Server
set -s focus-events on
set -s extended-keys on
set -s escape-time 0

# Title
set -g set-titles on
set -g set-titles-string "#{pane_title}"

# Start numbering at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# Split windows (opens in same directory as current pane)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Alt+hjkl to switch panes without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Reload config
unbind t
bind t source-file ~/.config/tmux/tmux.conf

# Reset window order 1,2,5 -> 1,2,3
unbind r
bind r move-window -r

# Shift+arrows to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Alt+number to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Vim style copying
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle 
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane
